apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.pipelinedata.appName }}
  name: {{ .Values.pipelinedata.appName }}


data:
  {{- range $key, $value := .Values.config }}
    {{- $key | upper }} : {{ $value | quote }}
    {{- end}}
